name: Docker

on:
  push:
    branches:
      - master
    tags:
      - v*

  pull_request:

env:
  IMAGE_NAME: deployer

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
            docker build .

  push:
    needs: build

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Find version
        id: version_step
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          [ "$VERSION" == "master" ] && VERSION=latest
          echo VERSION=$VERSION
          echo "::set-output name=version::${VERSION}"
           
      - name: Publish github
        run: |
          # Github package
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          echo IMAGE_ID=$IMAGE_ID

          docker tag $IMAGE_NAME $IMAGE_ID:${{ steps.version_step.outputs.version }}
          docker push $IMAGE_ID:${{ steps.version_step.outputs.version }}

      - name: Publish quay
        uses: ilteoood/docker_buildx@master
        with:
          publish: true
          imageName: quay.io/stenicio/deployer
          tag: ${{ steps.version_step.outputs.version }}
          dockerServer: quay.io
          dockerUser: ${{ secrets.QUAY_USER }}
          dockerPassword: ${{ secrets.QUAY_TOKEN }}